<?php
return [
    'adminEmail' => 'p@kkh.go.th',
    'supportEmail' => 'p@kkh.go.th',
    'user.passwordResetTokenExpire' => 3600,
    'siteName'=>'nRefer@MOPH',
    'siteDesc'=>'ระบบส่งผู้ป่วยรักษาต่อเนื่อง',
    'version'=>'2.0.0-5905.28.el7',
    'officeName'=>'Ministry of Public Health',
    'officeTHName'=>'กระทรวงสาธารณสุข',
    'officeTHNameAbbr'=>'สธ',
    'officeAbbr'=>'MOPH',
    'officeVision'=>'ภายในทศวรรษต่อไป คนไทยทุกคนจะมีสุขภาพแข็งแรงเพิ่มขึ้น เพื่อสร้างความเจริญเติบโตทางเศรษฐกิจของประเทศ ทั้งทางตรงและทางอ้อมอย่างยั่งยืน',
    'thMonth'=>['','มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'],
    'thMonthAbbr'=>['*err*','มค.','กพ.','มค.','เมย.','พค.','มิย.','กค.','สค.','กย.','ตค.','พย.','ธค.'],
    'EncryptKeyLen'=>6,
    'EncryptLeftString'=>19,
    'table_std_prefix'=>'',
    'table_ext_prefix'=>'ext_',
    'table_lib_prefix'=>'lib_',
    'table_report_prefix'=>'rep_',
    'tableStandard'=>[
        'person'=>['hospcode','pid'],
        'address'=>['hospcode','pid'],
        'home'=>['hospcode','pid'],
        'service'=>['hospcode','pid','seq'],
        'diagnosis_opd'=>['hospcode','pid','seq'],
        'procedure_opd'=>['hospcode','pid','seq'],
        'charge_opd'=>['hospcode','pid','seq'],
        'drug_opd'=>['hospcode','pid','seq'],
        'admission'=>['hospcode','pid','an'],
        'diagnosis_ipd'=>['hospcode','pid','an'],
        'procedure_ipd'=>['hospcode','pid','an'],
        'charge_ipd'=>['hospcode','pid','an'],
        'drug_ipd'=>['hospcode','pid','an'],
    ],
    'serverMaintenance'=>false,
    'statusCodesGroup' => ['1'=>'Informational','2'=>'Success','3'=>'Redirection','4'=>'Client Error','5'=>'Server Error'],
    'statusCodes' => ['100'=>'Continue','101'=>'Switching Protocols','102'=>'Processing (WebDAV)',
                '200'=>'OK','201'=>'Created','202'=>'Accepted','203'=>'Non-Authoritative Information','204'=>'No Content',
                '205'=>'Reset Content','206'=>'Partial Content','207'=>'Multi-Status (WebDAV)',
                '208'=>'Already Reported (WebDAV)','226'=>'IM Used','300'=>'Multiple Choices',
                '301'=>'Moved Permanently','302'=>'Found','303'=>'See Other','304'=>'Not Modified',
                '305'=>'Use Proxy','306'=>'(Unused)','307'=>'Temporary Redirect',
                '308'=>'Permanent Redirect (experiemental)',
                '400'=>'Bad Request',
                '401'=>'Unauthorized','402'=>'Payment Required','403'=>'Forbidden','404'=>'Not Found',
                '405'=>'Method Not Allowed','406'=>'Not Acceptable','407'=>'Proxy Authentication Required',
                '408'=>'Request Timeout','409'=>'Conflict','410'=>'Session gone or token expire',
                '411'=>'Length Required','412'=>'Precondition Failed','413'=>'Request Entity Too Large',
                '414'=>'Request-URI Too Long','415'=>'Unsupported Media Type','416'=>'Requested Range Not Satisfiable',
                '417'=>'Expectation Failed','418'=>'I am a teapot (RFC 2324)','420'=>'Enhance Your Calm (Twitter)',
                '422'=>'Unprocessable Entity (WebDAV)','423'=>'Locked (WebDAV)','424'=>'Failed Dependency (WebDAV)',
                '425'=>'Reserved for WebDAV','426'=>'Upgrade Required','428'=>'Precondition Required',
                '429'=>'Too Many Requests','431'=>'Request Header Fields Too Large','444'=>'No Response (Nginx)',
                '449'=>'Retry With (Microsoft)','450'=>'Blocked by Windows Parental Controls (Microsoft)',
                '451'=>'Unavailable For Legal Reasons','499'=>'Client Closed Request (Nginx)','500'=>'Internal Server Error',
                '501'=>'Not Implemented or Server Maintenance period',
                '502'=>'Bad Gateway',
                '503'=>'Service Unavailable or this version expired',
                '504'=>'Gateway Timeout',
                '505'=>'HTTP Version Not Supported','506'=>'Variant Also Negotiates (Experimental)',
                '507'=>'Insufficient Storage (WebDAV)','508'=>'Loop Detected (WebDAV)',
                '509'=>'Bandwidth Limit Exceeded (Apache)','510'=>'Not Extended','511'=>'Network Authentication Required',
                '598'=>'Network read timeout error','599'=>'Network connect timeout error'],
];
